# Generated by Django 4.2.17 on 2024-12-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredient', through='api.RecipeIngredients', to='api.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
